apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: pointofsale
data:
  APP_ENV: "kubernetes"
  DB_DRIVER: "postgres"
  DB_HOST: "postgres"
  DB_HOST_MIGRATE: "postgres"
  DB_PORT: "5432"
  DB_NAME: "POINT_OF_SALE"
  POSTGRES_DB: "POINT_OF_SALE"
  DB_MAX_OPEN_CONNS: "50"
  DB_MAX_IDLE_CONNS: "10"
  DB_CONN_MAX_LIFETIME: "30m"
  DB_SEEDER: "false"
  APP_LOGGER: "production"

  OTEL_ENDPOINT: "otel-collector.pointofsale.svc.cluster.local:4317"
  KAFKA_BROKERS: "kafka.pointofsale.svc.cluster.local:9092"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_CLUSTER_ENABLED: "true"
  REDIS_CLUSTER_ENDPOINTS: "redis-cluster-0.redis-cluster-headless.pointofsale.svc.cluster.local:6379,redis-cluster-1.redis-cluster-headless.pointofsale.svc.cluster.local:6379,redis-cluster-2.redis-cluster-headless.pointofsale.svc.cluster.local:6379,redis-cluster-3.redis-cluster-headless.pointofsale.svc.cluster.local:6379,redis-cluster-4.redis-cluster-headless.pointofsale.svc.cluster.local:6379,redis-cluster-5.redis-cluster-headless.pointofsale.svc.cluster.local:6379"

  GRPC_AUTH_ADDR: auth.pointofsale.svc.cluster.local:50051
  GRPC_ROLE_ADDR: role.pointofsale.svc.cluster.local:50052
  GRPC_MERCHANT_ADDR: merchant.pointofsale.svc.cluster.local:50054
  GRPC_TRANSACTION_ADDR: transaction.pointofsale.svc.cluster.local:50058
  GRPC_CASHIER_ADDR: cashier.pointofsale.svc.cluster.local:50061
  GRPC_CATEGORY_ADDR: category.pointofsale.svc.cluster.local:50062
  GRPC_PRODUCT_ADDR: product.pointofsale.svc.cluster.local:8086
  GRPC_ORDER_ADDR: order.pointofsale.svc.cluster.local:8084
  GRPC_ORDER_ITEM_ADDR: order-item.pointofsale.svc.cluster.local:8085

  GRPC_AUTH_PORT: "50051"
  GRPC_ROLE_PORT: "50052"
  GRPC_MERCHANT_PORT: "50054"
  GRPC_TRANSACTION_PORT: "50058"
  GRPC_CASHIER_PORT: "50061"
  GRPC_CATEGORY_PORT: "50062"
  GRPC_PRODUCT_PORT: "8086"
  GRPC_ORDER_PORT: "8084"
  GRPC_ORDER_ITEM_PORT: "8085"

  SECRET_KEY: "yantopedia"
  DB_URL: "postgres://DRAGON:DRAGON@postgres:5432/POINT_OF_SALE"
