apiVersion: v1
kind: Service
metadata:
  name: order-item
  namespace: pointofsale
spec:
  selector:
    app: order-item
  ports:
    - name: grpc
      port: 8085
      targetPort: 8085
  type: ClusterIP
