package io.example.common.grpc;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

import io.vertx.core.Future;
import io.vertx.grpc.common.ServiceMethod;
import io.vertx.grpc.server.GrpcServer;

/**
 * Binds a generated Vert.x gRPC service handler onto a {@link GrpcServer} with
 * proper error → status propagation.
 *
 * <p>Background: the server stubs generated by the Vert.x gRPC protoc plugin
 * (4.5.x) hardcode {@code GrpcStatus.INTERNAL} on <em>any</em> handler failure
 * (their {@code onFailure} lambda ignores the throwable). A domain exception
 * such as {@code UnauthorizedException} (which maps to UNAUTHENTICATED) would
 * therefore reach the client as INTERNAL → the gateway could never return 401.
 *
 * <p>This class is a drop-in replacement for the generated
 * {@code bindAll(GrpcServer)}: it discovers every RPC method of the handler's
 * generated interface, resolves the matching {@link ServiceMethod} constant,
 * and translates the failed future through {@link GrpcStatusMapper} before
 * ending the response.
 *
 * <p>Usage in a verticle:
 * <pre>{@code
 * GrpcServer grpcServer = GrpcServer.server(vertx);
 * GrpcServerBinder.bindAll(grpcServer, queryHandler);
 * GrpcServerBinder.bindAll(grpcServer, commandHandler);
 * }</pre>
 */
public final class GrpcServerBinder {

  private GrpcServerBinder() {
  }

  /**
   * Binds every RPC method of the generated gRPC interface(s) implemented by
   * {@code service} onto {@code server}.
   *
   * @throws IllegalArgumentException when {@code service} does not implement
   *         any generated {@code *GrpcServer} interface
   */
  public static void bindAll(GrpcServer server, Object service) {
    List<BoundMethod> methods = discoverMethods(service);
    if (methods.isEmpty()) {
      throw new IllegalArgumentException(
          "No generated gRPC service interface found on " + service.getClass().getName());
    }
    for (BoundMethod bound : methods) {
      bind(server, service, bound);
    }
  }

  /**
   * Discovers the RPC methods of the generated {@code *GrpcServer} interface(s)
   * implemented by {@code service}. Exposed as package-private for tests.
   */
  static List<BoundMethod> discoverMethods(Object service) {
    List<BoundMethod> result = new ArrayList<>();
    for (Class<?> iface : service.getClass().getInterfaces()) {
      Class<?> generated = iface.getEnclosingClass();
      if (generated == null || !generated.getName().endsWith("GrpcServer")) {
        continue;
      }
      for (Method method : iface.getMethods()) {
        if (!Future.class.isAssignableFrom(method.getReturnType())
            || method.getParameterCount() != 1) {
          continue;
        }
        result.add(new BoundMethod(generated, method));
      }
    }
    return result;
  }

  @SuppressWarnings({"rawtypes", "unchecked"})
  private static void bind(GrpcServer server, Object service, BoundMethod bound) {
    ServiceMethod serviceMethod = resolveServiceMethod(bound);

    server.callHandler(serviceMethod, request -> request.handler(payload -> {
      // Parent service spans to the gateway's trace (W3C traceparent metadata
      // injected by the gateway's ResilientGrpcClient) so Jaeger shows one
      // end-to-end trace across REST → gRPC hops (gap #24).
      try (io.opentelemetry.context.Scope scope =
               TraceContextExtractor.extract(request.headers()).makeCurrent()) {
        Future future = invoke(service, bound.method, payload);
        future
            .onSuccess(response -> request.response().end(response))
            .onFailure(err -> request.response()
                .status(GrpcStatusMapper.of((Throwable) err))
                .end());
      }
    }));
  }

  private static ServiceMethod resolveServiceMethod(BoundMethod bound) {
    String fieldName = Character.toUpperCase(bound.method.getName().charAt(0))
        + bound.method.getName().substring(1);
    try {
      Field field = bound.generated.getField(fieldName);
      return (ServiceMethod) field.get(null);
    } catch (ReflectiveOperationException e) {
      throw new IllegalStateException("Cannot resolve ServiceMethod '" + fieldName
          + "' on " + bound.generated.getName(), e);
    }
  }

  private static Future invoke(Object service, Method method, Object payload) {
    try {
      return (Future) method.invoke(service, payload);
    } catch (ReflectiveOperationException e) {
      throw new IllegalStateException("Failed to invoke " + method.getName()
          + " on " + service.getClass().getName(), e);
    }
  }

  /** A generated {@code ServiceMethod} constant plus the handler method it maps to. */
  static final class BoundMethod {
    final Class<?> generated;
    final Method method;

    BoundMethod(Class<?> generated, Method method) {
      this.generated = generated;
      this.method = method;
    }
  }
}
